version: '3.4'

volumes:
  l2_data:

services:
  l2:
    image: 001138754299.dkr.ecr.us-west-2.amazonaws.com/nitro-node:v3.6.7-a7c9f1e
    platform: linux/amd64
    ports:
      - "8545:8545"
      - "8546:8546"
    volumes:
      - "${PWD}/nodeConfig.json:/config/nodeConfig.json"
      - l2_data:/home/user/.arbitrum
    entrypoint:
      - "/usr/local/bin/nitro"
      - --conf.file=/config/nodeConfig.json
      - --node.staker.enable
      - --node.staker.strategy=Watchtower
      - --execution.forwarding-target=wss://nodeops-orchestrator-network.calderachain.xyz/ws
      - --node.feed.input.url=wss://nodeops-orchestrator-network.calderachain.xyz/feed      
      - --node.data-availability.rest-aggregator.urls="https://nodeops-orchestrator-network.calderachain.xyz/rest-aggregator"
      - --parent-chain.connection.url=[Insert your Arbitrum One RPC here]

